name: Test Haskell Library

on:
  pull_request:
  push:
    paths-ignore:
      - "**.el"

jobs:
  tests:

    name: Execute Unit Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10'
          cabal-version: '3.2.0.0'
      - name: Build
        run: cabal new-build --enable-tests
      - name: Run Tests
        run: cabal new-test --enable-tests
